#!/bin/sh
if [ $# -lt 2 ]
then echo "A process name and an executable to run must both be supplied"; exit 1;
fi
TMPDIR=$(mktemp -d)
ln -s "$(which $2)" "$TMPDIR/$1"
bash -c "until pidof $1 > /dev/null; do sleep 0.1; done && rm -rf $TMPDIR" & exec $TMPDIR/$1 ${@:3}
